version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: List files
          command: ls -la
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests with coverage
          command: |
            coverage run -m unittest discover
            coverage report -m
            coverage html
      - store_artifacts:
          path: htmlcov
          destination: coverage-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
